name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # 将此更改为你的默认分支名称，如果不是main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chenmins/ddns:latest  # 更改为你的Docker Hub用户名和镜像名称
          build-args:
            GITHUB_USERNAME: ${{ github.repository_owner }}
            REPO_NAME: ${{ github.repository }}
            VERSION: ${{ github.ref_name }}
            BINARY_NAME: ddns.${{ github.ref_name }}.Linux_x86_64.tar.gz  # 根据你的二进制文件名和版本模式修改
